compact: true
framework:
  - dockerfile
quiet: true
directory: .
skip-check:
  # ---------------------------------------------------------------------------------------
  #                                     Overkill
  # ---------------------------------------------------------------------------------------

  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2

  # Ensure port 22 is not exposed
  - CKV_DOCKER_1
