version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
    - echo getting image name
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
    - echo "image tag $IMAGE_TAG"
  build:
    commands:    
    - export PROJECTNAME="sftp"
    - echo "Building..... $PROJECTNAME"
    - export VERSION="latest"
    - echo "Building $PROJECTNAME Version $VERSION"
    - docker build -t 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$VERSION .
  post_build:
    commands:
    - docker push 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$VERSION
    - docker tag 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$VERSION 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$IMAGE_TAG
    - docker push 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$IMAGE_TAG
    - printf '[{"name":"TrxSFTP","imageUri":"%s"}]' 648548064017.dkr.ecr.us-east-1.amazonaws.com/transactrx/$PROJECTNAME:$IMAGE_TAG > taskdefinition.json
artifacts:
    files: taskdefinition.json