FROM debian:bullseye

# Steps done in one RUN layer:
# - Install packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN apt-get update && \
    apt-get -y install openssh-server && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config_2222 /etc/ssh/sshd_config
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /
COPY files/startup_scripts/load_env_host_key.bash /etc/sftp.d/load_env_host_key.bash

RUN chmod +x /etc/sftp.d/*

EXPOSE 2222

ENTRYPOINT ["/entrypoint"]
