apiVersion: v1
kind: Service
metadata:
  labels:
    app: sftp-client
  name: sftp-client
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    app: sftp-client
  type: NodePort
