name: build

on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: tests/shunit2

  debian:
    needs: verify
    uses: ./.github/workflows/build-image.yml
    with:
      update-check: "apt-get update >/dev/null && apt-get upgrade -s | grep '^Inst' || true"
    secrets: inherit
