name: Push image
on:
  workflow_call:

env:
  image_tag: sftp:debian

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # for shunit2

      - name: setup docker
        id: docker_setup
        uses: cardlay/.github/actions/docker-setup@main
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build docker image for test image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.docker_setup.outputs.dockerx_builder }} # use the same later to use local caching of buildx
          file: Dockerfile
          push: false
          load: true
          platforms: linux/amd64 # no need to test both arm and amd manifests + output type `docker` does not support multiple platforms when loading
          tags: ${{ env.image_tag }}-test

      - name: Test image
        run: tests/run ${{ env.image_tag }}-test

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.docker_setup.outputs.dockerx_builder }}
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/cardlay/${{ env.image_tag }}
