name: Staging Docker Build

on: workflow_dispatch

jobs:
  staging-docker-build:
    name: Staging Docker Build
    uses: demarque/github-action-templates/.github/workflows/template-docker-build.yaml@main
    with:
      REF: master
      GCR_HOSTNAME: gcr.io
      GCP_PROJECT: demarque
      IMAGE: market-sftp
      GITHUB_SHA: ${{ github.sha }}
      TARGET_ENV: staging
      REPOSITORY_NAME: ${{ github.event.repository.name }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEMARQUE }}
      GH_CI_CD_TOKEN: ${{ secrets.GH_CI_CD_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}